version: '3.9'


services:
  app:
    container_name: portifolio-app
    build: 
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    
  db:
    image: postgres:latest
    container_name: portifolio-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=portifolio_db_dev
      - POSTGRES_USER=davi
      - POSTGRES_PASSWORD=dev1234
      
    volumes:
      - postgres_data:/var/lib/postgres/data

volumes:
  postgres_data:
    